[package]
name = "const_hashmap"
version = "0.1.1"
edition = "2024"
authors = ["Alan Volker <volkeralan12@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Compile-time hash map for any const-hashable key"
repository = "https://github.com/cjperron/const_hashmap"
keywords = ["const", "map", "hash", "compile-time", "hashmap"]
rust-version = "1.86.0"


[workspace]
members = ["const_hashmap_macros"]
resolver = "3"

[dependencies]
const_hashmap_macros = { version = "0.1.0" }

[features]
default = []
derive = ["const_hashmap_macros/derive"]

[badges]
maintenance = { status = "experimental" }
